services:
  - type: web
    name: whisker-cart
    env: php
    plan: free
    buildCommand: ./render-build.sh
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: errorlog
      - key: DB_CONNECTION
        fromDatabase:
          name: whisker-db
          property: connection
      - key: DB_HOST
        fromDatabase:
          name: whisker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: whisker-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: whisker-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: whisker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: whisker-db
          property: password

databases:
  - name: whisker-db
    plan: free
    databaseName: whisker_cart
    user: whisker_user
